export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILURE = 'AUTH_FAILURE';
export const AUTH_STATUS = 'AUTH_STATUS';
export const AUTH_UPDATE = 'AUTH_UPDATE';
export const AUTH_CLEAN = 'AUTH_CLEAN';

// Notifications
export const NOTIFICATIONS_UPDATE = 'NOTIFICATIONS_UPDATE';
export const NOTIFICATIONS_CLEAN_ALL = 'NOTIFICATIONS_CLEAN_ALL';

// NEWS
export const NEWS_REQUEST = 'NEWS_REQUEST';
export const NEWS_SUCCESS = 'NEWS_SUCCESS';
export const NEWS_FAILURE = 'NEWS_FAILURE';
export const NEWS_UPDATE = 'NEWS_UPDATE';

// PUBLIC INFO
export const PUBLIC_INFO_REQUEST = 'PUBLIC_INFO_REQUEST';
export const PUBLIC_INFO_SUCCESS = 'PUBLIC_INFO_SUCCESS';
export const PUBLIC_INFO_FAILURE = 'PUBLIC_INFO_FAILURE';
export const PUBLIC_INFO_UPDATE = 'PUBLIC_INFO_UPDATE';
