export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILURE = 'AUTH_FAILURE';
export const AUTH_STATUS = 'AUTH_STATUS';
export const AUTH_UPDATE = 'AUTH_UPDATE';
export const AUTH_CLEAN = 'AUTH_CLEAN';

// Notifications
export const NOTIFICATIONS_UPDATE = 'NOTIFICATIONS_UPDATE';
export const NOTIFICATIONS_CLEAN_ALL = 'NOTIFICATIONS_CLEAN_ALL';
