export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILURE = 'AUTH_FAILURE';
export const AUTH_STATUS = 'AUTH_STATUS';
export const AUTH_UPDATE = 'AUTH_UPDATE';
export const AUTH_CLEAN = 'AUTH_CLEAN';

// Notifications
export const NOTIFICATIONS_UPDATE = 'NOTIFICATIONS_UPDATE';
export const NOTIFICATIONS_CLEAN_ALL = 'NOTIFICATIONS_CLEAN_ALL';

// NEWS
export const NEWS_REQUEST = 'NEWS_REQUEST';
export const NEWS_SUCCESS = 'NEWS_SUCCESS';
export const NEWS_FAILURE = 'NEWS_FAILURE';
export const NEWS_UPDATE = 'NEWS_UPDATE';
export const NEWS_SET = 'NEWS_SET';
export const NEWS_CACHE_CLEAN = 'NEWS_CACHE_CLEAN';
export const NEWS_UPDATE_LIKES = 'NEWS_UPDATE_LIKES';

// PUBLIC INFO
export const PUBLIC_INFO_REQUEST = 'PUBLIC_INFO_REQUEST';
export const PUBLIC_INFO_SUCCESS = 'PUBLIC_INFO_SUCCESS';
export const PUBLIC_INFO_FAILURE = 'PUBLIC_INFO_FAILURE';
export const PUBLIC_INFO_UPDATE = 'PUBLIC_INFO_UPDATE';

// ACTIVITY
export const ACTIVITY_REQUEST = 'ACTIVITY_REQUEST';
export const ACTIVITY_SUCCESS = 'ACTIVITY_SUCCESS';
export const ACTIVITY_FAILURE = 'ACTIVITY_FAILURE';
export const ACTIVITY_UPDATE = 'ACTIVITY_UPDATE';

// CLOCK
export const CLOCK_REQUEST = 'CLOCK_REQUEST';
export const CLOCK_UPDATE = 'CLOCK_UPDATE';
export const CLOCK_SUCCESS = 'CLOCK_SUCCESS';
export const CLOCK_FAILURE = 'CLOCK_FAILURE';
